export const DorkTemplates = [
  { name: 'Exposed Database Files', query: 'ext:sql | ext:dbf | ext:mdb' },
  { name: 'Directory Listing', query: 'intitle:"index of" "parent directory"' },
  { name: 'Configuration Files', query: 'ext:env | ext:config | ext:yml site:example.com' },
  { name: 'Log Files', query: 'ext:log "password" | "error"' },
  { name: 'SSH Keys', query: 'intitle:"index of" id_rsa | id_dsa' },
  { name: 'Excel Passwords', query: 'ext:xls | ext:xlsx "password" | "login"' },
  { name: 'WordPress Backup', query: 'ext:sql inurl:wp-content/backup' },
  { name: 'Git Folders', query: 'inurl:"/.git" -github.com' },
  { name: 'AWS Credentials', query: 'ext:txt | ext:env "AKIA"' },
  { name: 'PHP Info', query: 'ext:php intitle:"phpinfo()" "PHP Version"' },
  { name: 'Jira Tickets', query: 'inurl:"/secure/Dashboard.jspa"' },
  { name: 'Open Webcams', query: 'inurl:"view.shtml" | inurl:"view/index.shtml"' },
  { name: 'Admin Login Pages', query: 'intitle:"login" "admin"' },
  { name: 'FTP Servers', query: 'intitle:"index of" "ftp"' },
  { name: 'SQL Dumps', query: '"insert into" ext:sql' },
  { name: 'Resume/CV', query: 'intitle:"resume" | intitle:"cv" ext:pdf' },
  { name: 'Trello Boards', query: 'site:trello.com/b/ "password"' },
  { name: 'Pastebin Credentials', query: 'site:pastebin.com "password" | "api_key"' },
  { name: 'Jenkins Servers', query: 'intitle:"Dashboard [Jenkins]"' },
  { name: 'Docker Registries', query: 'inurl:"/v2/_catalog"' },
  { name: 'Sensitive Documents', query: 'ext:doc | ext:pdf "confidential" | "strictly private"' },
];
